# ----------- CONFIGURABLE START -----------
title:            "Gilbert blog"
description:      ""
url:              https://blog.gilbertwong.co # 域名
signoff:          "Gilbert" # Your name
google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 15
paginate_path: "gilbertpage:num"
plugins: [jekyll-paginate]
links:
  - name:         首页
    url:          /
    external:     false
  - name:         归档
    url:          /archives
    external:     false
  - name:         关于
    url:          /about
    external:     false
  - name:         标签
    url:          /tags
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
